export const HOME_ACTION = {
  GET_DATA_HOME: 'GET_DATA_HOME',
  SUCCESS_GET_HOME: 'SUCCESS_GET_HOME',
  DELL_DATA: 'DELL_DATA',
  SUCCESS_DEll: 'SUCCESS_DEll',
  ADD_DATA: 'ADD_DATA',
  SUCCESS_ADD: 'SUCCESS_ADD',
  GET_DATA_BYID: 'GET_DATA_BYID',
  SUCCESS_GET_BYID: 'SUCCESS_GET_BYID',
  EDIT_DATA: 'EDIT_DATA',
  SUCCESS_EDIT_DATA: 'SUCCESS_EDIT_DATA',
};
