export const SEARCH_ACTION = {
  SEARCH_DATA_COUNTRY: 'SEARCH_DATA_COUNTRY',
  SET_MY_LOCATION: 'SET_MY_LOCATION',
  GET_MY_LOCATION: 'GET_MY_LOCATION',
  SUCCESS_GET_MYLOCATION: 'SUCCESS_GET_MYLOCATION',
  SUCCESS_SEARCH_DATA_COUNTRY: 'SUCCESS_SEARCH_DATA_COUNTRY',
};
